# Generated by Django 4.2.2 on 2023-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=8)),
                ('Pincode', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
