# Generated by Django 4.2.2 on 2023-08-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookApp', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
