# Generated by Django 4.2.2 on 2023-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('Job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Published_on', models.DateField()),
                ('Last_date', models.DateField()),
                ('Designation', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('JobType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_id', models.IntegerField()),
                ('Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Applied_Date', models.DateField()),
                ('Cv', models.FileField(upload_to='GasBooking/media/JobCv')),
            ],
        ),
    ]
