# Generated by Django 4.2.2 on 2023-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_addjob_applyforjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='Applied_Date',
            field=models.DateField(default=''),
        ),
    ]
