# Generated by Django 4.2.2 on 2023-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_alter_applyforjob_applied_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSignUp',
            fields=[
                ('Employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=20)),
                ('Emp_address', models.CharField(max_length=20)),
                ('Emp_gender', models.CharField(max_length=20)),
                ('Emp_age', models.IntegerField()),
                ('Emp_phone', models.IntegerField(max_length=15)),
                ('Emp_location', models.CharField(max_length=20)),
                ('Emp_District', models.CharField(max_length=20)),
                ('Emp_Email', models.EmailField(max_length=15)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
