# Generated by Django 4.2.2 on 2023-08-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0007_transportor_alter_employeesignup_emp_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportor',
        ),
    ]
