# Generated by Django 4.2.2 on 2023-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0009_transportorsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForConnection',
            fields=[
                ('Con_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Con_number', models.IntegerField()),
                ('Con_name', models.CharField(max_length=20)),
                ('Con_Address', models.CharField(max_length=50)),
                ('Con_gender', models.CharField(max_length=10)),
                ('Con_phone', models.IntegerField()),
                ('Con_location', models.CharField(max_length=20)),
                ('Con_District', models.CharField(max_length=20)),
                ('Con_pincode', models.IntegerField()),
                ('Con_for', models.CharField(max_length=10)),
                ('Con_Est_name', models.CharField(max_length=20)),
                ('Con_Est_Address', models.CharField(max_length=50)),
                ('Con_Id_proof', models.FileField(upload_to='GasBooking/media/ConnectionIdProof')),
                ('Con_Email', models.EmailField(max_length=20)),
            ],
        ),
    ]
