# Generated by Django 4.2.2 on 2023-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0010_applyforconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforconnection',
            name='Is_activate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applyforconnection',
            name='Con_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
