# Generated by Django 4.2.2 on 2023-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0011_applyforconnection_is_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Description', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('ForType', models.CharField(max_length=20)),
                ('CylinderImage', models.FileField(upload_to='GasBooking/media/CylinderImage')),
            ],
        ),
    ]
