# Generated by Django 4.2.2 on 2023-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0012_addcylinder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcylinder',
            name='CylinderImage',
            field=models.ImageField(upload_to='GasBooking/media/CylinderImage'),
        ),
    ]
