# Generated by Django 4.2.2 on 2023-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0015_cylinderbook_transportor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderbook',
            name='Transportor_Name',
            field=models.CharField(default='not taken Yet', max_length=20),
        ),
    ]
