# Generated by Django 4.2.2 on 2023-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0016_alter_cylinderbook_transportor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderbook',
            name='Total_booking',
            field=models.IntegerField(default=0),
        ),
    ]
