# Generated by Django 4.2.2 on 2023-08-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0017_cylinderbook_total_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcylinder',
            name='id',
        ),
        migrations.AddField(
            model_name='addcylinder',
            name='Cylinder_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
