# Generated by Django 4.2.2 on 2023-08-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0019_alter_applyforconnection_con_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcylinder',
            name='Cylinder_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
