# Generated by Django 4.2.2 on 2023-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0020_alter_addcylinder_cylinder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderbook',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cylinderbook',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cylinderbook',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
