# Generated by Django 4.2.2 on 2023-08-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0021_cylinderbook_address_cylinderbook_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderbook',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
