# Generated by Django 4.2.2 on 2023-08-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0022_cylinderbook_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportorsignup',
            name='t_is_activated',
            field=models.CharField(max_length=10),
        ),
    ]
