# Generated by Django 4.2.2 on 2023-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0023_alter_transportorsignup_t_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccessories',
            fields=[
                ('Accessories_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Acess_title', models.CharField(max_length=30)),
                ('Acess_Desc', models.CharField(max_length=50)),
                ('Acess_price', models.IntegerField()),
                ('Acess_image_cover', models.ImageField(upload_to='GasBooking/media/Accessories/Cover')),
                ('Acess_2ndimage', models.ImageField(upload_to='GasBooking/media/Accessories/2ndImage')),
                ('Acess_3rdimage', models.ImageField(upload_to='GasBooking/media/Accessories/3rdImage')),
            ],
        ),
    ]
