# Generated by Django 4.2.2 on 2023-08-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0024_addaccessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAccessories',
            fields=[
                ('Booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Conn_no', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=20)),
                ('Product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('Delivery_address', models.CharField(max_length=50)),
                ('Payment', models.CharField(max_length=20)),
                ('OrderDate', models.DateField()),
            ],
        ),
    ]
