# Generated by Django 4.2.2 on 2023-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0025_bookaccessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookaccessories',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookaccessories',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookaccessories',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bookaccessories',
            name='Transportor_Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookaccessories',
            name='Transportor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookaccessories',
            name='Transportor_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
