# Generated by Django 4.2.2 on 2023-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0026_bookaccessories_phone_bookaccessories_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderbook',
            name='Delivered_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
