# Generated by Django 4.2.2 on 2023-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0028_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='Job_position',
            field=models.CharField(default='', max_length=20),
        ),
    ]
