# Generated by Django 4.2.2 on 2023-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0029_applyforjob_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='applyforjob',
            name='Job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
