# Generated by Django 4.2.2 on 2023-09-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0030_remove_applyforjob_id_alter_applyforjob_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='status',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
