# Generated by Django 4.2.2 on 2023-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0031_applyforjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportorsignup',
            name='Daily_booking',
            field=models.IntegerField(default=0),
        ),
    ]
