# Generated by Django 4.2.2 on 2023-09-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0032_transportorsignup_daily_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DailyLimit', models.IntegerField()),
            ],
        ),
    ]
